export default function ({ params }: { params: { slug: string } }) {
    // slug is basically for dynamic routing
  return (
    <>
      <title>Pricing UI</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
